# -*- coding: utf-8 -*-
"""Advent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RNLYR5MiFdp5g0Qv_-VNR9F-yPRy-47k
"""

office = open('/content/input.txt', 'r')
list1, list2 = [], []
total = 0
counter = 0
for lines in office:
  temp1, temp2 = map(int,lines.split())
  list1.append(temp1)
  list2.append(temp2)

list1.sort()
list2.sort()
for offices in range(len(list1)):
  total += abs(list1[offices]-list2[offices])
print(total)

for offices in list1:
  for similarity in list2:
    if offices==similarity:
      counter+=offices

print(counter)

